### ISSUE TITLE
Refactoring code

### ISSUE THREAD

**Issue by getzze** [mengqvist/DNApy#39]
Hi,
I would like to suggest to refactor the code to make it easier to modify and implement new features.
See the modifications in my fork:
https://github.com/getzze/DNApy/tree/master/DNApy
I already did several changes, and I would like to propose some improvements:
 - [x] make the project a python module. This allows to call the program directly with `DNApy` from the linux console, and also to do `import DNApy` to have access to all the function from the python console. I made the `setup.py` file for that, and created the `__init__.py` in each subdirectories.
To install, go to the folder where `setup.py` is and type `python setup.py develop`.

 - [x] use the relative import from python3. It needs to add `from __future__ import absolute_import` at the beginning of each file (see my changes).

 - [x] use os.path.join to join paths, it is safer and platform independent (see my changes)

 - [x] beware of circular dependencies. I found out that `colcol.py` needed `wsvg.py` and reciprocally. Also the GUI is not working with wxpython3, I suspect because update_ownUI is called in an infinite loop.

 - [ ] allow to use a (newer) version already installed of `pyperclip`.

 - [x] put all the files for the gui in a separate folder. For clarity.

 - [x] put the settings files in a separate folder. And use another format for the settings. Using `execfile` is not very good. I would say that the settings should be stored in a json file (it's like a python dict) and imported using the json module (https://docs.python.org/2/library/json.html). Also per-user settings should be stored in `~/.DNApy/` instead of the module arborescence, to be easier to modify (and to avoid permission issues if DNApy is a module). See https://github.com/mengqvist/DNApy/issues/37

 - [x] for the compatibility with wxpython3 (see https://github.com/mengqvist/DNApy/issues/36), I found one problem in base_class.py, line 107
after `Size  = self.ClientSize`, adding a line `Size = (max(Size[0], 1), max(Size[1], 1))` made the plasmid widget appear. Maybe it can help to solve other problems.

 - [x] add a logger using the `logging` module. It is very easy to use, and it can help dramatically to track down bugs.

I hope these changes can help to simplify the package to make it easier for other people to modify also.

**Comment by openpaul** [comment]
Nice changes. I am totally behind them. I guess @mengqvist  will also approve of them?
The last weeks he was a little bit occupied, but new people in the project might be cool to get it all going more fluidly.

**Comment by mengqvist** [comment]
Hi getzze. I love your feedback! These are all very nice suggestions and I'll see about implementing them. As openpaul mentioned I sadly do not have much time for this project of late, so any help is always welcome. I will try to be better about merging pull requests from now on.

**Comment by mengqvist** [comment]
So I merged my branch with yours and now very little works. There's a whole range of seemingly un-related bugs. I just spent 3 hours trying to sort it out but to no avail. I like the way you're going with this, but I'll have to see if I can revert back to the version that actually worked.

**Comment by getzze** [comment]
Yes, with these changes I only managed to open the GUI. But in fact there was a big problem, the module `genbank` was called in several files and it was called using attributes (like `genbank.restriction_sites`), which cannot work.
In my branch develop I changed this, by creating a class `genbank` (different from the file `genbank`), so you can call its attributes.

I have two problems now, the dna editor panel in the GUI does not work and I cannot load files.

**Comment by mengqvist** [comment]
Yeah, I had the same issues with the dna editor panel and when loading files.
For the file loading the problem seemed to be that no color could be found for the features. The values from the settings file did not work any more.

**Comment by getzze** [comment]
The `settings`, `variables` and `font` files should definitively be removed, and a json should be used instead.
Also, in some of my tests, my .gb file was erased, that should not be the case no? A new file should be created instead of modifying the original.
 
Did you try to run the GUI from my develop branch?

**Comment by openpaul** [comment]
Risking to out myself: Do I always have to install the package first to test it? Or is there an easy way to launch it directly without running
```
python setup.py install
```
Just wondering. Will test it later. If I find and/or fix a bug, can I create a pull request for your development branch, so that it will be merged later into the new master?

**Comment by getzze** [comment]
Now it is a module, so you cannot run it directly. But you can use
```
python setup.py develop
```
http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install
Then you can edit your code normally, and still run `DNApy` from the console to launch the GUI.

The main repo should stay this one. mengqvist could create a `develop` branch where we can create a pull request.

**Comment by openpaul** [comment]
thanks, 
as of now I only receive a huge error message when running your development branch. but I will have a look on the weekend.
I would be glad if this refactoring would work.
