### ISSUE TITLE
Does not launch on Ubuntu 15.04

### ISSUE THREAD

**Issue by SilverWingedSeraph** [mengqvist/DNApy#40]
I installed the software using the included instructions (install dependencies, git clone, run main.py). Output was:

```
/usr/bin/xsel
Segmentation fault (core dumped)
```

**Comment by openpaul** [comment]
Hello, nice that you try to run it. What is your version of python-wxgtk?

Currently it does only work with python-wxgtk2.8 not with python-wxgtk3.0. that results in the error you describe.

**Comment by getzze** [comment]
try installing xclip:
sudo apt-get install xclip

**Comment by SilverWingedSeraph** [comment]
Works with xclip. Maybe add that to the README?

**Comment by openpaul** [comment]
So you installed xclip and gtk was not the issue?
Just to be clear what to add to the README

**Comment by SilverWingedSeraph** [comment]
That's correct, I installed everything already in the README plus xclip and
it worked fine.

**Comment by openpaul** [comment]
Ok,
see pull request https://github.com/mengqvist/DNApy/pull/41
Hope @mengqvist will merge this soon.
